ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ cuda.version.major }}.{{ cuda.version.minor }}-{{ cuda.cudnn.target }}-{{ cuda.os.distro }}{{ cuda.os.version }}{{ cuda.tag_suffix }}
LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

{% if cuda.version.major | int == 8 -%}
RUN echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu{{ cuda.os.version | replace(".",
"") }}/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list

{% endif -%}

ENV CUDNN_VERSION {{ cuda.cudnn.version }}
LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

RUN apt-get update && apt-get install -y --no-install-recommends \
    libcudnn{{ cuda.cudnn.version[0] }}=$CUDNN_VERSION-1+cuda{{ cuda.version.major }}.{{ cuda.version.minor }} \
{% if cuda.cudnn.target == "devel" -%}
    libcudnn{{ cuda.cudnn.version[0] }}-dev=$CUDNN_VERSION-1+cuda{{ cuda.version.major }}.{{ cuda.version.minor }} \
{% endif -%}
    && \
    apt-mark hold libcudnn{{ cuda.cudnn.version[0] }} && \
    rm -rf /var/lib/apt/lists/*
