ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ cuda.version.major }}.{{ cuda.version.minor }}-base-{{ cuda.os.distro }}{{ cuda.os.version }}{{ cuda.tag_suffix }}
LABEL maintainer "NVIDIA CORPORATION <cudatools@nvidia.com>"

ENV NCCL_VERSION {{ cuda.nccl_version }}

RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-libraries-$CUDA_PKG_VERSION \
{% if cuda.version.major | int == 9 and cuda.version.minor | int == 0 -%}
    cuda-cublas-{{ cuda.version.major }}-{{ cuda.version.minor }}={{ cuda.version.full }}.4-1 \
{% endif -%}
{% if cuda.version.major | int == 9 and cuda.version.minor | int == 2 or cuda.version.major | int >= 10 -%}
    cuda-nvtx-$CUDA_PKG_VERSION \
{% endif -%}
{% if cuda.version.major | int == 10 and cuda.version.minor | int >= 1 -%}
    libcublas10=10.2.{{ cuda.version.minor }}.{{ cuda.version.build }}-1 \
{% endif -%}
    libnccl2=$NCCL_VERSION-1+cuda{{ cuda.version.major }}.{{ cuda.version.minor }} && \
    apt-mark hold libnccl2 && \
    rm -rf /var/lib/apt/lists/*
