ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ cuda.version.major }}.{{ cuda.version.minor }}-base-{{ cuda.os.distro }}{{ cuda.os.version }}{{ cuda.tag_suffix }}
LABEL maintainer "NVIDIA CORPORATION <sw-cuda-installer@nvidia.com>"

RUN yum install -y \
        cuda-libraries-$CUDA_PKG_VERSION \
{% if cuda.version.major | int == 9 -%}
    {% if cuda.version.minor | int == 0 -%}
        cuda-cublas-{{ cuda.version.major }}-{{ cuda.version.minor }}-{{ cuda.version.full }}.4-1 \
    {% endif -%}
{% endif -%}
{% if cuda.version.major | int == 9 and cuda.version.minor | int == 2 or cuda.version.major | int >= 10 -%}
        cuda-nvtx-$CUDA_PKG_VERSION \
    {% if cuda.version.major | int == 10 and cuda.version.minor | int >= 1 -%}
        libcublas10-10.2.{{ cuda.version.minor }}.{{ cuda.version.build }}-1 \
    {% endif -%}
{% endif -%}
        && \
    rm -rf /var/cache/yum/*
